version: "3.8"
services: 
  reacthook:
    build: .
    container_name: zzz
    ports: 
      - "3000:3000"
    # volumes:
    #   - .:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "8001:8001"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    depends_on:
      - reacthook

